### ISSUE TITLE
ASSIGN needs an initialize and reset of the voice knob to function on reloading a patch.

### ISSUE THREAD

**Issue by jph-wacheski** [bogaudio/BogaudioModules#150]
ASSIGN is a great module!   The only problem is, it stops rotating, sending all 8 voices, in my case, at once when the patch is reloaded.  I used Right click menu Initialize and reset the voice knob to 8 and function returns,. .

**Comment by mdemanett** [comment]
Hey, glad you like it.  Do you have a sample patch where the problem happens?  That'd help track it down.  Thanks!

**Comment by jph-wacheski** [comment]
Should show the issue with just this. Seems my analysis was incorrect, the bug is related to closing and then reopening Rack.  So when you open this, the poly rotation should be working, however close rack, and when it reloads the file the rotation stops with all voices fire simultaneously.  Thanks for looking into it,. you make some fine modules that I use often, thanks for that too.

[Assign_reload_test.zip](https://github.com/bogaudio/BogaudioModules/files/5366998/Assign_reload_test.zip)

**Comment by mdemanett** [comment]
I'm still not able to make the problem happen, using the patch and restarting a bunch of times.  That said, looking at the code, there's something that might cause this.  A test build with a maybe-fix should show up [on the latest test release](https://github.com/bogaudio/BogaudioModules/releases/tag/v1.1.34-test7), for each platform.  Please give it a shot and let me know.

If it doesn't work -- or actually, even if it does, because there might be a larger problem -- here are the usual dumb questions:  
  1. What OS are you on?
  2. How many CPUs in your machine, and what's your Engine->Threads menu setting in Rack?  (Sometimes threads cause weird problems.)
  3. Are you on Rack v1.1.6, and is it the official download?  (Not built from sources or something?)
  4. When the problem's happening, what's it doing in detail?  All gates are firing at once, but at the clock rate?  All the same pitches?  Do the pitches change with the clock?  A screen grab of PolyScope when it's happening might help.  (PolyScope is awesome, btw, I didn't know about it.)

**Comment by jph-wacheski** [comment]
here is a video of the behavior.  This is win10, Rack v1.1.6, 3.3ghz quad core 8gb memory machine,. this starts on the reload bug and then initialize the module. 
[VCV Rack v1.1.6 - _Assign_reload_test.vcv 2020-10-14 08-19-17.zip](https://github.com/bogaudio/BogaudioModules/files/5378124/VCV.Rack.v1.1.6.-._Assign_reload_test.vcv.2020-10-14.08-19-17.zip)

**Comment by mdemanett** [comment]
Thanks for the video, and toggling through the sample rate menu -- turns out the problem shows up when the sample rate isn't the default.  The fix should show up on the Rack library build soon.

**Comment by mdemanett** [comment]
This is released on the library.

**Comment by jph-wacheski** [comment]
Great!  Thank you so much.
